# Pre-Built Installers are here (https://github.com/kasmtech/workspaces-images/tree/develop/src/ubuntu/install)

ARG BASE_TAG="1.13.0"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

# Reference the Install Directories
ENV UNBUNTU_INSTALL_FILES src/ubuntu/install
ENV CUSTOM_INSTALL_FILES src/custom/install
ENV CUSTOM_WORKSPACE_CUSTOMIZATIONS workspace_customizations

# ---------------------------------------------------------------------------- #
#                                Customizations                                #
# ---------------------------------------------------------------------------- #

# --------------------------- Install Atomic Wallet -------------------------- #

COPY $CUSTOM_INSTALL_FILES/atomic_wallet/install_atomic_wallet.sh $INST_SCRIPTS/atomic_wallet/install_atomic_wallet.sh
RUN bash $INST_SCRIPTS/atomic_wallet/install_atomic_wallet.sh  && rm -rf $INST_SCRIPTS/atomic_wallet/install_atomic_wallet.sh

# --------------------------------- PostSetup -------------------------------- #
COPY $CUSTOM_INSTALL_FILES/atomic_wallet/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN cp /usr/share/extra/backgrounds/bg_kasm.png /usr/share/extra/backgrounds/bg_default.png
RUN apt-get remove -y xfce4-panel

# ---------------------------------------------------------------------------- #
#                              End Customizations                              #
# ---------------------------------------------------------------------------- #

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000